name: auto-merge PRs by dependabot or gliff-ai-robot
on:
  workflow_call:
    secrets:
      ROBOT_PAT:
        required: true

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]'}}
    steps:
      - name: fetch dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: "${{ secrets.ROBOT_PAT }}"
      - name: enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.ROBOT_PAT}}
  gliff-ai-robot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'gliff-ai-robot'}}
    steps:
      - name: enable auto-merge for gliff-ai-robot
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.ROBOT_PAT}}
